---
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.pdkignore:
  paths:
    - /.*.yml
    - /pdk.yaml
    - /.pmtignore
    - /fetch_checksums.sh
    - /.git*
    - /.editorconfig
    - /provision.yaml
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
Gemfile:
  optional:
    ':development':
      - gem: 'net-ftp'
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
