name: "ci"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'AUTHORS'
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "./.github/workflows/module_ci.yml"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "./.github/workflows/module_acceptance.yml"
    secrets: "inherit"
